/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SlotImage {
    'src': string;
  }
  interface SlotMachine {
    'duration': number;
    'spin': () => Promise<void>;
    'stop': (ms: number) => Promise<number>;
  }
}

declare global {


  interface HTMLSlotImageElement extends Components.SlotImage, HTMLStencilElement {}
  var HTMLSlotImageElement: {
    prototype: HTMLSlotImageElement;
    new (): HTMLSlotImageElement;
  };

  interface HTMLSlotMachineElement extends Components.SlotMachine, HTMLStencilElement {}
  var HTMLSlotMachineElement: {
    prototype: HTMLSlotMachineElement;
    new (): HTMLSlotMachineElement;
  };
  interface HTMLElementTagNameMap {
    'slot-image': HTMLSlotImageElement;
    'slot-machine': HTMLSlotMachineElement;
  }
}

declare namespace LocalJSX {
  interface SlotImage {
    'src'?: string;
  }
  interface SlotMachine {
    'duration'?: number;
  }

  interface IntrinsicElements {
    'slot-image': SlotImage;
    'slot-machine': SlotMachine;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'slot-image': LocalJSX.SlotImage & JSXBase.HTMLAttributes<HTMLSlotImageElement>;
      'slot-machine': LocalJSX.SlotMachine & JSXBase.HTMLAttributes<HTMLSlotMachineElement>;
    }
  }
}


